### ISSUE TITLE
clicking on anchor link shows nothing and yields console error

### ISSUE THREAD

**Issue by martenson** [molly/citation-needed-scripts#1]
reproducible e.g. on https://www.citationneeded.news/issue-50/ 

I did not check the code to see what exactly is supposed to happen but in case it is useful note that the link itself uses `reference-x` as ID and the footnote has id of `footnote-x`. 

```
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLElement.onAnchorClick (sidenotes.js:93:1)
onAnchorClick @ sidenotes.js:93
```

chrome 121.0, macos

**Comment by molly** [comment]
Thank you! Fixed.

**Comment by KernelLeak** [comment]
I just wanted to report this same problem - clicking on sidenotes now works as it should, but the footnotes still produce an error in Firefox's console:

```
15:43:24.506 Uncaught TypeError: can't access property "classList", document.getElementById(...) is null
    onAnchorClick sidenotes.js:128
    sidenotes sidenotes.js:153
    setInitialSettings settings.js:189
    settings settings.js:214
    <anonymous> signup.js:1
sidenotes.js:128
```

And even if it worked - it still might highlight the footnote (if that's even what's supposed to happen), but I don't see how it would jump down to the footnote, with the event basically being cancelled...

**Comment by molly** [comment]
@KernelLeak Can you check if it's fixed now with https://github.com/molly/citation-needed-theme/commit/9542ae0c6809ac461ff0e802aa884c9f73171769 ? 

When there is a sidenote for the footnote or reference, clicking the anchor should highlight the sidenote corresponding to the anchor without jumping someone to the bottom of the page. If the sidenotes aren't shown, they should be brought to the bottom of the page.

**Comment by KernelLeak** [comment]
Seeing as the footnotes are now working on [Issue 50](https://www.citationneeded.news/issue-50/), I'd say the problem is fixed - thanks! :)

**Comment by molly** [comment]
Thanks for letting me know!
